### ISSUE TITLE
How to config in my editor?

### ISSUE THREAD

**Issue by jingyuexing** [wasm-lsp/wasm-lsp-server#207]
I use sublime text ,not VSCode.
i config options like this:
```
"wasm":{
	"command":[
    "wasm-lsp"
  ],
	"selector":"source.wat | source.wast"
}
```
but nothing happened

**Comment by silvanshade** [comment]
For selector, you probably need to change to `"selector":"wasm.wat | wasm.wast"` since those are the language-id's the server uses. Hopefully that's enough for it to work, but I so far I haven't tested the server with any other editors.

Hope that helps.

**Comment by jingyuexing** [comment]
useless

**Comment by silvanshade** [comment]
It's unfortunate you can't get it to work. When I have time I'll try to take a look at using the server with sublime text. Thanks for the feedback though.
